services:
  - type: web
    name: finance-tracker
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: apache2-foreground
    rootDir: public
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        sync: false